version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD= ''
      - MYSQL_DATABASE= 'lcdd_db'
      - MYSQL_ALLOW_EMPTY_PASSWORD= 'yes'
    ports:
      - 3306:3306


  backend:
    image: bygranizo/lcdd_backend
    ports:
      - 8443:8443
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL= 'jdbc:mysql://db:3306/lcdd_db'
      - SPRING_DATASOURCE_USERNAME= 'root'
      - SPRING_DATASOURCE_PASSWORD= ''